-- MySQL Script generated by MySQL Workbench
-- Tue May 24 16:28:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `staffId` INT NOT NULL,
  `fullName` VARCHAR(80) NULL,
  `email` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `job` VARCHAR(45) NULL,
  PRIMARY KEY (`staffId`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Books` (
  `isbn` INT NOT NULL,
  `booktitle` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  PRIMARY KEY (`isbn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reader` (
  `readerId` INT NOT NULL,
  `fullName` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`readerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BorrowedBooks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BorrowedBooks` (
  `BorrowedId` int not null,
  `DateCollected` date not null,
  `Deadline` date not null,
  `UserId` int not null,
  `StaffId` int not null,
  `BookId` int not null
  )
ENGINE = InnoDB;


